import React, { useState } from 'react';
import { api } from '../../api';
import { buildReportModel, buildExport, downloadBlob } from '../../utils/expenseExport';

const FORMATS = [
  { id: 'pdf', label: 'PDF', icon: 'ti-file-type-pdf', hint: 'Full detail table, branded' },
  { id: 'xlsx', label: 'Excel', icon: 'ti-file-spreadsheet', hint: 'Multi-sheet workbook' },
  { id: 'csv', label: 'CSV', icon: 'ti-file-text', hint: 'Raw rows for any tool' },
  { id: 'summary', label: 'Executive summary', icon: 'ti-presentation', hint: 'One-page client-facing' },
];

/**
 * Export expenses for one business or all businesses combined, in four formats.
 * The same generated bytes are used for both Download and Save to Documents, so what the
 * client receives and what is filed are guaranteed identical.
 */
export default function ExpenseExportModal({
  businessId,
  businessName = 'Business',
  businesses = [],           // [{id, name}] — enables the "all businesses" scope
  defaultFrom = '',
  defaultTo = '',
  onClose,
  onSaved,                   // called after a successful Save to Documents
}) {
  const [scope, setScope] = useState('business'); // 'business' | 'all'
  const [format, setFormat] = useState('pdf');
  const [from, setFrom] = useState(defaultFrom);
  const [to, setTo] = useState(defaultTo);
  const [busy, setBusy] = useState('');           // 'download' | 'save'
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const isAll = scope === 'all';

  const loadModel = async () => {
    const params = {};
    if (from) params.from = from;
    if (to) params.to = to;

    const [expenses, summary] = isAll
      ? await Promise.all([api.listAllBusinessExpenses(params), api.getAllBusinessExpenseSummary(params)])
      : await Promise.all([
          api.listBusinessExpenses(businessId, params),
          api.getBusinessExpenseSummary(businessId, params),
        ]);

    const names = new Map(businesses.map((b) => [b.id, b.name]));
    return buildReportModel({
      expenses: Array.isArray(expenses) ? expenses : [],
      summary,
      scopeLabel: isAll ? 'All businesses' : businessName,
      from, to,
      businessNames: names,
    });
  };

  const run = async (mode) => {
    try {
      setBusy(mode);
      setError('');
      setNotice('');
      const model = await loadModel();
      if (!model.rows.length) {
        setError('No expenses in this range to export.');
        return;
      }
      const { blob, filename } = await buildExport(format, model);

      if (mode === 'download') {
        downloadBlob(blob, filename);
        setNotice(`Downloaded ${filename}`);
      } else {
        // Saved into the CURRENT business's Documents even for a combined report, so there is
        // one predictable home for it.
        const file = new File([blob], filename, { type: blob.type });
        await api.uploadBusinessDocument(businessId, file, {
          docType: 'TAX',
          label: filename.replace(/\.[^.]+$/, ''),
          note: `Expense report · ${model.scopeLabel} · ${model.period}`,
        });
        setNotice('Saved to this business’s Documents.');
        onSaved?.();
      }
    } catch (err) {
      setError(err?.message || 'Export failed.');
    } finally {
      setBusy('');
    }
  };

  return (
    <div className="expense-modal-overlay" role="dialog" aria-modal="true" aria-label="Export expenses"
      onMouseDown={(e) => { if (e.target === e.currentTarget) onClose?.(); }}>
      <div className="expense-modal" onMouseDown={(e) => e.stopPropagation()}>
        <div className="expense-modal-head">
          <div>
            <div className="section-title" style={{ marginBottom: 2 }}>
              <i className="ti ti-download" style={{ marginRight: 6, color: 'var(--tv-forest-light)' }}></i>
              Export expenses
            </div>
            <div className="item-sub">Download it, or file it in this business&rsquo;s Documents.</div>
          </div>
          <button className="icon-btn" onClick={onClose} title="Close"><i className="ti ti-x"></i></button>
        </div>

        <div className="expense-modal-body">
          {error && (
            <div className="card" style={{ borderLeft: '4px solid var(--tv-negative)', color: 'var(--tv-negative)', fontSize: 13, marginBottom: 12 }}>
              {error}
            </div>
          )}
          {notice && (
            <div className="card" style={{ borderLeft: '4px solid var(--tv-positive)', fontSize: 13, marginBottom: 12 }}>
              <i className="ti ti-circle-check" style={{ color: 'var(--tv-positive)', marginRight: 6 }}></i>{notice}
            </div>
          )}

          <div className="form-group">
            <label className="form-label">Scope</label>
            <div className="seg-control">
              <button className={`seg-btn ${scope === 'business' ? 'active' : ''}`} onClick={() => setScope('business')}>
                {businessName}
              </button>
              <button className={`seg-btn ${isAll ? 'active' : ''}`} onClick={() => setScope('all')}
                disabled={businesses.length < 2}
                title={businesses.length < 2 ? 'Add another business to combine reports' : 'Combine every business into one report'}>
                All businesses{businesses.length > 1 ? ` (${businesses.length})` : ''}
              </button>
            </div>
          </div>

          <div className="grid-2">
            <div className="form-group">
              <label className="form-label">From</label>
              <input type="date" className="form-input" value={from} onChange={(e) => setFrom(e.target.value)} />
            </div>
            <div className="form-group">
              <label className="form-label">To</label>
              <input type="date" className="form-input" value={to} onChange={(e) => setTo(e.target.value)} />
            </div>
          </div>
          <div className="item-sub" style={{ marginTop: -6, marginBottom: 12 }}>
            Leave both blank to export all time.
          </div>

          <div className="form-group">
            <label className="form-label">Format</label>
            <div className="expense-format-grid">
              {FORMATS.map((f) => (
                <button key={f.id} type="button"
                  className={`expense-format-card ${format === f.id ? 'active' : ''}`}
                  onClick={() => setFormat(f.id)}>
                  <i className={`ti ${f.icon}`}></i>
                  <div>
                    <div className="expense-format-label">{f.label}</div>
                    <div className="item-sub">{f.hint}</div>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="expense-modal-foot">
          <div className="item-sub">{isAll ? 'Combined across every business' : businessName}</div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-secondary btn-sm" onClick={() => run('download')} disabled={!!busy}>
              <i className={`ti ${busy === 'download' ? 'ti-loader spin' : 'ti-download'}`}></i>
              {busy === 'download' ? 'Preparing…' : 'Download'}
            </button>
            <button className="btn btn-primary btn-sm" onClick={() => run('save')} disabled={!!busy}>
              <i className={`ti ${busy === 'save' ? 'ti-loader spin' : 'ti-folder'}`}></i>
              {busy === 'save' ? 'Saving…' : 'Save to Documents'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
