-- Append-only user-activity audit log.
CREATE TABLE audit_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(64),            -- JWT subject (user id) or NULL/anonymous for pre-auth
    actor_type   VARCHAR(20),            -- USER | SYSTEM | ANONYMOUS
    action       VARCHAR(160) NOT NULL,  -- e.g. auth.login.success, GET /api/v1/accounts
    service      VARCHAR(60),            -- target service (derived) or 'gateway'
    method       VARCHAR(10),
    path         VARCHAR(512),
    status       INT,
    source_ip    VARCHAR(64),
    user_agent   VARCHAR(512),
    latency_ms   INT,
    outcome      VARCHAR(20),            -- SUCCESS | FAILURE | DENIED
    metadata     TEXT,                   -- optional JSON for extra context
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_user_id    ON audit_events (user_id);
CREATE INDEX idx_audit_created_at ON audit_events (created_at);
CREATE INDEX idx_audit_action     ON audit_events (action);
CREATE INDEX idx_audit_user_time  ON audit_events (user_id, created_at);
