-- Signed checkpoints: periodic snapshots that pin the chain head.
--
-- WHY, given the chain is already keyed (V5): HMAC stops someone who can write to this database
-- but doesn't hold the key. It does NOT stop someone holding both — they can recompute the whole
-- chain. A checkpoint closes that by pinning the head at a point in time somewhere the DB writer
-- doesn't control, so rewriting history means also rewriting every copy of the checkpoint.
--
-- This table is the convenience copy. The ANCHOR is the same value emitted to the service log at
-- INFO on every checkpoint — logs ship off this box and are retained separately, so the two can be
-- compared. A checkpoint that lives only in the database it protects proves nothing.
CREATE TABLE audit_checkpoints (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_head    VARCHAR(64) NOT NULL,   -- entry_hash of the newest event at checkpoint time
    last_event_id BIGINT,                 -- id of that event (null when the log is empty)
    event_count   BIGINT NOT NULL,        -- number of chained events at that moment
    signature     VARCHAR(64) NOT NULL,   -- HMAC over the fields above + created_at
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_checkpoints_created ON audit_checkpoints (created_at);
