-- Phase 4 — Inventory & COGS foundation
CREATE TABLE business_inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    business_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(60),
    cost_price DECIMAL(18,2),
    sell_price DECIMAL(18,2),
    on_hand INT NOT NULL DEFAULT 0,
    reorder_point INT,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_inventory_items_biz_user ON business_inventory_items (business_id, user_id, name);
