-- Phase 5 — Payroll & 1099 contractors foundation
CREATE TABLE business_contractors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    business_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(40),
    tax_form VARCHAR(24) NOT NULL DEFAULT '1099',
    amount DECIMAL(18,2),
    payment_terms VARCHAR(40),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_contractors_biz_user ON business_contractors (business_id, user_id, name);
