-- Phase 5 — Business team member multi-user collaboration table
CREATE TABLE business_team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    business_id BIGINT NOT NULL,
    member_user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'VIEWER',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_team_members_biz_user ON business_team_members (business_id, user_id, member_user_id);