-- Financial ops: an append-only ledger + maker-checker adjustments.
--
-- This is the money surface the ops portal has been building up to. It lands AFTER separate ops
-- identity (P1), permissions (P2) and the actor/target audit trail (P3) — deliberately, so the
-- first refund anyone issues is already fully attributable.
--
-- It lives in payment-service because this is the only service that actually moves money (Stripe,
-- bill-pay, subscriptions). Account-aggregation reads someone else's money; business-financials
-- tracks invoices. Ops calls in here; this stays the system of record.

-- ---- The ledger ---------------------------------------------------------------------------
-- APPEND-ONLY. Nothing here is ever updated or deleted: a correction is a NEW entry that reverses
-- the original and points at it. That is what makes the financial history auditable rather than
-- merely current — "what does this customer owe" and "how did it get that way" are the same query.
CREATE TABLE ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         VARCHAR(64)  NOT NULL,
    entry_type      VARCHAR(32)  NOT NULL,  -- CHARGE|REFUND|CREDIT|ADJUSTMENT|DISPUTE_HOLD|DISPUTE_RELEASE|REVERSAL
    -- Signed minor units: positive = owed to us, negative = owed to the customer. Integer cents,
    -- never floating point — a rounding error in a ledger is a rounding error in someone's money.
    amount_cents    BIGINT       NOT NULL,
    currency        VARCHAR(3)   NOT NULL DEFAULT 'USD',
    -- Running balance at the moment this entry was appended. Denormalised on purpose: it makes the
    -- ledger readable as a statement, and it pins what the balance WAS, so a later bug in the
    -- summing logic can't silently rewrite history.
    balance_after   BIGINT       NOT NULL,
    source          VARCHAR(32)  NOT NULL,  -- STRIPE|BILLPAY|SUBSCRIPTION|OPS_ADJUSTMENT
    external_ref    VARCHAR(128),           -- Stripe charge/refund id, when there is one
    reverses_id     BIGINT,                 -- the entry this one reverses (corrections only)
    adjustment_id   BIGINT,                 -- the ops_adjustments row that produced this entry
    -- NON-NEGOTIABLE. Execution retries after a timeout are normal; double-refunding a customer
    -- because of one is not. Every write carries a key derived from the adjustment.
    idempotency_key VARCHAR(128) UNIQUE,
    memo            VARCHAR(255),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(64),            -- ops_users id, or 'SYSTEM'
    FOREIGN KEY (reverses_id) REFERENCES ledger_entries (id)
);

CREATE INDEX idx_ledger_user_time ON ledger_entries (user_id, created_at);
CREATE INDEX idx_ledger_adjustment ON ledger_entries (adjustment_id);

-- ---- Maker-checker adjustments ------------------------------------------------------------
-- An ops-initiated money movement is a REQUEST that goes through a state machine, never a direct
-- write to the ledger:
--   DRAFT -> PENDING_APPROVAL -> APPROVED -> EXECUTING -> EXECUTED
--                             \-> REJECTED           \-> FAILED
CREATE TABLE ops_adjustments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         VARCHAR(64) NOT NULL,   -- the CUSTOMER whose money this moves
    kind            VARCHAR(32) NOT NULL,   -- REFUND|CREDIT|MANUAL_ADJUSTMENT|GOODWILL|DISPUTE_ACCEPT
    amount_cents    BIGINT      NOT NULL,
    currency        VARCHAR(3)  NOT NULL DEFAULT 'USD',
    -- From a fixed vocabulary, not free text. Free text alone is unqueryable, and "how much did we
    -- refund for BILLING_ERROR last quarter" is a question that always eventually gets asked.
    reason_code     VARCHAR(48) NOT NULL,
    reason_note     TEXT        NOT NULL,   -- the narrative; required
    ticket_ref      VARCHAR(64),
    status          VARCHAR(24) NOT NULL,
    requested_by    VARCHAR(64) NOT NULL,   -- ops_users id
    requested_at    TIMESTAMP   NOT NULL,
    decided_by      VARCHAR(64),            -- MUST differ from requested_by (see below)
    decided_at      TIMESTAMP,
    decision_note   TEXT,
    executed_at     TIMESTAMP,
    ledger_entry_id BIGINT,                 -- set once EXECUTED
    failure_reason  TEXT,
    -- FOUR EYES, at the storage layer.
    -- The service enforces this too, but a CHECK constraint is what makes it true even for a code
    -- path that forgets, a future refactor, or a hand-written UPDATE. It is the single
    -- highest-value control here: it is what stops one compromised or malicious agent from
    -- draining money on their own.
    CONSTRAINT chk_adjustment_four_eyes CHECK (decided_by IS NULL OR decided_by <> requested_by)
);

CREATE INDEX idx_adjustments_status ON ops_adjustments (status, requested_at);
CREATE INDEX idx_adjustments_user ON ops_adjustments (user_id, requested_at);
CREATE INDEX idx_adjustments_requester ON ops_adjustments (requested_by, requested_at);

ALTER TABLE ledger_entries
    ADD CONSTRAINT fk_ledger_adjustment FOREIGN KEY (adjustment_id) REFERENCES ops_adjustments (id);

-- ---- Anomalies ----------------------------------------------------------------------------
-- Raised by nightly rules, decided by a supervisor. Rules that catch real things, not a dashboard
-- widget: repeat refunds, an agent far outside their peer group (the insider case), ledger drift
-- against the provider (integration bugs), refund-after-failed-payments (card testing).
CREATE TABLE ops_anomalies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule          VARCHAR(48)  NOT NULL,
    severity      VARCHAR(16)  NOT NULL,   -- LOW|MEDIUM|HIGH
    user_id       VARCHAR(64),             -- the customer involved, when the rule is about one
    actor_id      VARCHAR(64),             -- the ops user involved, for agent-behaviour rules
    detail        TEXT         NOT NULL,   -- what was found, in words a human can act on
    status        VARCHAR(16)  NOT NULL DEFAULT 'OPEN', -- OPEN|ACCEPTED|DISMISSED
    decided_by    VARCHAR(64),
    decided_at    TIMESTAMP,
    decision_note TEXT,
    -- Stops the nightly job re-raising the same finding every night until someone looks at it.
    -- A queue that cries wolf gets ignored, which is the same as not having one.
    dedupe_key    VARCHAR(128) UNIQUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_anomalies_status ON ops_anomalies (status, created_at);

-- ---- Tunables -----------------------------------------------------------------------------
-- DB-editable so the threshold can be retuned from evidence (the real refund distribution) rather
-- than from the guess baked in here. Column names avoid `key`/`value` — both reserved in H2, which
-- dev/test run against these same migrations.
CREATE TABLE ops_finance_config (
    config_key   VARCHAR(64)  PRIMARY KEY,
    config_value VARCHAR(255) NOT NULL,
    description  VARCHAR(255)
);

-- $25. Below this, routine goodwill credits execute immediately; at or above, a supervisor must
-- approve. Requiring approval for EVERYTHING sounds safer but isn't: it gets routed around by busy
-- agents, and a control everyone works around is worse than a sane threshold everyone respects.
-- Worth re-deriving from the actual Stripe refund distribution before treating 2500 as settled.
INSERT INTO ops_finance_config (config_key, config_value, description) VALUES
  ('adjustment.auto_approve_below_cents', '2500',
   'Adjustments strictly below this amount execute without a second approver. At or above, a holder of finance.adjustment.approve must approve.');
