-- Internal notes + escalations: the working memory of a support team.
--
-- Without these, everything an agent learns on a call is lost the moment they hang up, and the
-- next agent starts from zero — which is how a customer ends up explaining the same problem three
-- times. Notes are what make the 360 view a record rather than a snapshot.

CREATE TABLE ops_customer_notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(64) NOT NULL,   -- the CUSTOMER the note is about
    author_id  VARCHAR(64) NOT NULL,   -- ops_users id
    body       TEXT        NOT NULL,
    -- Pinned notes surface at the top of the record: "this customer has a payment dispute open",
    -- "do not offer another goodwill credit". The things the next agent must not miss.
    pinned     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
    -- No updated_at, and no UPDATE path: notes are append-only. An edited note is a note you can't
    -- trust in a dispute — a correction is a new note. Same reasoning as the ledger.
);

CREATE INDEX idx_ops_notes_user ON ops_customer_notes (user_id, created_at);

CREATE TABLE ops_escalations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(64) NOT NULL,   -- the CUSTOMER this is about
    raised_by     VARCHAR(64) NOT NULL,   -- ops_users id
    severity      VARCHAR(16) NOT NULL,   -- LOW|MEDIUM|HIGH
    summary       VARCHAR(255) NOT NULL,
    detail        TEXT,
    status        VARCHAR(16) NOT NULL DEFAULT 'OPEN',  -- OPEN|RESOLVED
    assigned_to   VARCHAR(64),            -- ops_users id, null = unassigned queue
    resolved_by   VARCHAR(64),
    resolved_at   TIMESTAMP,
    resolution    TEXT,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ops_escalations_status ON ops_escalations (status, created_at);
CREATE INDEX idx_ops_escalations_user ON ops_escalations (user_id, created_at);

-- The permissions that gate them. Consistent with the rule that a key ships with the endpoint that
-- honours it — these arrive with the notes/escalation routes, not before.
INSERT INTO ops_permissions (permission_key, category, description) VALUES
  ('customer.note.write',   'CUSTOMER', 'Add internal notes to a customer record, visible only to ops staff'),
  ('customer.escalate',     'CUSTOMER', 'Raise an escalation on a customer, and resolve one');

-- Front-line agents get both. This is the core of the job: notes and escalation ARE how support
-- works, and an agent who can read a record but not record what they found is only half useful.
INSERT INTO ops_role_permissions (role_key, permission_key) VALUES
  ('OPS_AGENT', 'customer.note.write'),
  ('OPS_AGENT', 'customer.escalate'),
  ('OPS_SUPERVISOR', 'customer.note.write'),
  ('OPS_SUPERVISOR', 'customer.escalate'),
  ('OPS_FINANCE', 'customer.note.write'),
  ('OPS_FINANCE', 'customer.escalate'),
  ('OPS_ADMIN', 'customer.note.write'),
  ('OPS_ADMIN', 'customer.escalate');

-- OPS_COMPLIANCE stays read-only by construction — it holds no *.write key, and that includes
-- these. Oversight observes; it does not participate.
