-- Caller verification & tiered disclosure.
--
-- The gap this closes: nothing proved the person on the phone is the customer before an agent
-- disclosed their data. Permissions gate what the AGENT may do; this gates what the CALLER has
-- proven. Both must pass. Design: DOCUMENTATION/proposals/ops-caller-verification.md.

-- One verification session per (agent, customer, call). Time-boxed and ephemeral: a caller
-- verified yesterday is not verified today. Kept as a row (not just in-memory) so the tier reached
-- and its expiry survive a request hop, and so a supervisor reviewing a call can see it.
CREATE TABLE ops_verification_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id     VARCHAR(64) NOT NULL,   -- ops_users id of the agent on the call
    customer_id  VARCHAR(64) NOT NULL,   -- the customer whose identity is being verified
    tier         INT         NOT NULL DEFAULT 0,  -- 0 unverified .. 3 step-up
    method       VARCHAR(24),            -- the method that reached the current tier (OTP | KBA | ...)
    started_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at  TIMESTAMP,              -- when it first passed T1+
    expires_at   TIMESTAMP   NOT NULL,   -- the tier drops to 0 after this
    -- A session frozen by "can't verify / suspicious" cannot be raised again this call — the agent
    -- has decided the caller is not who they claim, and one click shouldn't undo that.
    frozen       BOOLEAN     NOT NULL DEFAULT FALSE
);

-- The live session for a given agent+customer is the newest non-expired one.
CREATE INDEX idx_verif_session_lookup ON ops_verification_sessions (agent_id, customer_id, started_at);

-- Every attempt — pass OR fail — so repeated failures (the signal of an attack) are countable, and
-- so the disclosure timeline can show exactly how the caller was verified.
CREATE TABLE ops_verification_attempts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL,
    agent_id     VARCHAR(64) NOT NULL,
    customer_id  VARCHAR(64) NOT NULL,
    method       VARCHAR(24) NOT NULL,   -- OTP | KBA
    outcome      VARCHAR(16) NOT NULL,   -- PASS | FAIL
    detail       VARCHAR(255),           -- e.g. the KBA fact asked (never the answer)
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES ops_verification_sessions (id) ON DELETE CASCADE
);

CREATE INDEX idx_verif_attempt_fraud ON ops_verification_attempts (customer_id, outcome, created_at);

-- The disclosure-tier mapping: which action requires the caller to be at which tier.
--
-- DB-EDITABLE on purpose (config_key naming avoids the H2 reserved word `key`). "What needs what"
-- is then a table you can read and retune from evidence, not logic buried in controllers — the
-- same reasoning as the permission catalog and the auto-approve threshold. Seeded to the design's
-- tier table; adjust in place without a deploy.
CREATE TABLE ops_disclosure_tiers (
    action_key VARCHAR(64) PRIMARY KEY,
    min_tier   INT          NOT NULL,
    description VARCHAR(255)
);

INSERT INTO ops_disclosure_tiers (action_key, min_tier, description) VALUES
  ('customer.status',   1, 'Plan, is-a-payment-failing, account locked — non-sensitive status'),
  ('customer.data',     2, 'Balances, transactions, payment detail'),
  ('customer.pii',      2, 'Reveal SSN/EIN last-4'),
  ('customer.contact.change', 3, 'Change the registered email/phone — the account-takeover vector'),
  ('money.movement',    3, 'Refunds, credits, adjustments — the caller must be step-up verified');
